# Create Resource Group, vnet, and subnets.

# You need to create a file named /root/azure_creds.yaml with the following variables:
#
# subscription_id_var: "--your-subscription-id-here--"
# client_id_var: "--your-client-id-here--"
# tenant_var: "--your-tenant-here--"
# secret_var: "--your-secret-here--"

- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
   - /root/azure_creds.yaml
   - arm-template-vars.yaml

  tasks:
   - name: Create a resource group
     azure_rm_resourcegroup:
      name: "{{ rg_name }}"
      state: "{{ resource_state }}"
      location: "{{ location }}"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}" 
   
   - name: Create vnet
     azure_rm_virtualnetwork:
      name: "{{ vnetName }}"
      state: "{{ resource_state }}"
      address_prefixes_cidr: "{{ vnet_address_space }}"
      resource_group: "{{ rg_name }}"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"

   - name: Create mgmt subnet
     azure_rm_subnet:
      name: "{{ subnet1 }}"
      state: "{{ resource_state }}"
      resource_group: "{{ rg_name }}"
      virtual_network_name: "{{ vnetName }}"
      address_prefix_cidr: "{{ subnet1_range }}"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"

   - name: Create external subnet
     azure_rm_subnet:
      name: "{{ subnet2 }}"
      state: "{{ resource_state }}"
      resource_group: "{{ rg_name }}"
      virtual_network_name: "{{ vnetName }}"
      address_prefix_cidr: "{{ subnet2_range }}"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"

   - name: Create internal subnet
     azure_rm_subnet:
      name: "{{ subnet3 }}"
      state: "{{ resource_state }}"
      resource_group: "{{ rg_name }}"
      virtual_network_name: "{{ vnetName }}"
      address_prefix_cidr: "{{ subnet3_range }}"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"

