# Create Resource Group, vnet, and subnets.
#
# You need to create a file named azure_creds.yaml (update path below) with the following variables:
# 
# subscription_id_var: "--your-subscription-id-here--"
# client_id_var: "--your-client-id-here--"
# tenant_var: "--your-tenant-here--"
# secret_var: "--your-secret-here--"
# adminpass_var: "--bigip-admin-user-password--"
# license_var_1: "--bigip-registration-key--"

- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
   - /root/azure_creds.yaml

  tasks:
   - name: Create a resource group
     azure_rm_resourcegroup:
      name: bello_RG01
      state: present
      location: "UK South"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}" 
   
   - name: Create vnet
     azure_rm_virtualnetwork:
      name: vnet-01
      state: present
      address_prefixes_cidr: "10.3.0.0/16"
      resource_group: bello_RG01
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"

   - name: Create mgmt subnet
     azure_rm_subnet:
      name: mgmt
      state: present
      resource_group: bello_RG01
      virtual_network_name: vnet-01
      address_prefix_cidr: "10.3.0.0/24"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"

   - name: Create external subnet
     azure_rm_subnet:
      name: external
      state: present
      resource_group: bello_RG01
      virtual_network_name: vnet-01
      address_prefix_cidr: "10.3.1.0/24"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"

   - name: Create internal subnet
     azure_rm_subnet:
      name: internal
      state: present
      resource_group: bello_RG01
      virtual_network_name: vnet-01
      address_prefix_cidr: "10.3.2.0/24"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"

   - name: Create subnet01 subnet
     azure_rm_subnet:
      name: subnet01
      state: present
      resource_group: bello_RG01
      virtual_network_name: vnet-01
      address_prefix_cidr: "10.3.3.0/24"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"

   - name: Create subnet02 subnet
     azure_rm_subnet:
      name: subnet02
      state: present
      resource_group: bello_RG01
      virtual_network_name: vnet-01
      address_prefix_cidr: "10.3.4.0/24"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"

   - name: Create subnet03 subnet
     azure_rm_subnet:
      name: subnet03
      state: present
      resource_group: bello_RG01
      virtual_network_name: vnet-01
      address_prefix_cidr: "10.3.5.0/24"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"

   - name: Create subnet04 subnet
     azure_rm_subnet:
      name: subnet04
      state: present
      resource_group: bello_RG01
      virtual_network_name: vnet-01
      address_prefix_cidr: "10.3.6.0/24"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"

   - name: Create subnet05 subnet
     azure_rm_subnet:
      name: subnet05
      state: present
      resource_group: bello_RG01
      virtual_network_name: vnet-01
      address_prefix_cidr: "10.3.7.0/24"
      subscription_id: "{{ subscription_id_var }}"
      client_id: "{{ client_id_var }}"
      tenant: "{{ tenant_var }}"
      secret: "{{ secret_var }}"
