#Create via-api BIG-IP HA cluster in Azure

# You need to create a file named azure_creds.yaml (update path below) with the following variables:
#
# subscription_id_var: "--your-subscription-id-here--"
# client_id_var: "--your-client-id-here--"
# tenant_var: "--your-tenant-here--"
# secret_var: "--your-secret-here--"
# adminpass_var: "--bigip-admin-user-password--"
# license_var_1: "--bigip-registration-key--"
# license_var_2: "--bigip-registration-key--"

---

- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - /root/azure_creds.yaml

  tasks:
    - name: Azure Deploy to vnet-01
      azure_rm_deployment:
        state: present
#        state: absent
        subscription_id: "{{ subscription_id_var }}"
        resource_group_name: demo-lab
        template_link: "https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/v7.3.0.0/supported/failover/same-net/via-api/n-nic/existing-stack/byol/azuredeploy.json"
        #location: "UK South"
        location: "West US"
        client_id: "{{ client_id_var }}"
        tenant: "{{ tenant_var }}"
        secret: "{{ secret_var }}"
        parameters:
          adminUsername:
            value: azureuser
          authenticationType:
            value: password
          adminPasswordOrKey:
            value: "{{ adminpass_var }}"
          dnsLabel:
            value: via-api
          instanceName:
            value: f501
          instanceType:
            value: Standard_DS3_v2
          bigIpVersion:
            value: "15.0.100000"
          customImage:
            value: "OPTIONAL"
          bigIpModules:
            value: "ltm:nominal"
          imageName:
            value: AllTwoBootLocations
          licenseKey1:
            value: "{{ license_var_1 }}"
          licenseKey2:
            value: "{{ license_var_2 }}"
          numberOfExternalIps:
            value: 1
          provisionPublicIP:
            value: "Yes"
          numberOfAdditionalNics:
            value: 0
          vnetName:
            value: vnet-01
          vnetResourceGroupName:
            value: demo-lab
          mgmtSubnetName:
            value: mgmt
          mgmtIpAddressRangeStart:
            value: 10.3.0.10
          externalSubnetName:
            value: external
          externalIpSelfAddressRangeStart:
            value: 10.3.1.10
          externalIpAddressRangeStart:
            value: 10.3.1.100
          internalSubnetName:
            value: internal
          internalIpAddressRangeStart:
            value: 10.3.2.10
          declarationUrl:
            value: "NOT_SPECIFIED"
          managedRoutes:
            value: 0.0.0.0/0,10.3.0.0/24,10.3.1.0/24,10.3.2.0/24
          ntpServer:
            value: 0.pool.ntp.org
          timeZone:
            value: UTC
          restrictedSrcAddress:
            value: "*"
          tagValues:
            value:
              application: APP
              cost: COST
              environment: ENV
              group: GROUP
              owner: OWNER
          allowUsageAnalytics:
            value: 'No'
          tenantId:
            value: "{{ tenant_var }}"
          clientId:
            value: "{{ client_id_var }}"
          servicePrincipalSecret:
            value: "{{ secret_var }}"
